site_name: UC Psychology Graduate Student Wiki
site_url: https://uc-psychology.github.io/grad-student-wiki/
repo_url: https://github.com/UC-Psychology/grad-student-wiki
site_dir: 'site'
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.indexes
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  language: en
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav: 
  - Home: 
    - index.md
    - Get Started Contributing: contributing.md
  - How To's: 
    - howtos/index.md
    - Add a Page to the Wiki: howtos/add_documentation_page.md
    - Use Git: howtos/git.md
    - GitHub Co-Pilot: howtos/copilot.md
  - Glossary: glossary.md
  - Reviews: 
    - reviews/index.md
    - codeacademy: reviews/codecademy.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
